package com.github.timeeidolon.logiccodeplugin.cleanup

import com.github.timeeidolon.logiccodeplugin.settings.ReportPluginSettings
import com.google.gson.Gson
import com.intellij.openapi.components.Service
import com.intellij.openapi.project.Project
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption
import java.security.MessageDigest
import kotlin.io.path.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.deleteIfExists
import kotlin.io.path.exists
import kotlin.io.path.isRegularFile
import kotlin.io.path.readText
import kotlin.io.path.writeText

/**
 * Tracks all files generated by this plugin under the configured output dir (default: `docs/`),
 * and supports safe cleanup that won't delete user-modified files.
 *
 * Manifest location: `<outputDir>/.logic-code/manifest.json`.
 */
@Service(Service.Level.PROJECT)
class GeneratedFilesManifestService {

    data class Record(
        val relativePath: String,
        val sha256: String,
        val sizeBytes: Long,
        val recordedAtMs: Long = System.currentTimeMillis()
    )

    data class CleanupResult(
        val deleted: Int,
        val skippedModified: Int,
        val skippedMissing: Int,
        val errors: Int
    )

    private data class Persisted(
        val schemaVersion: Int = 1,
        val records: List<Record> = emptyList()
    )

    private val gson = Gson()
    private val lock = Any()

    companion object {
        fun getInstance(project: Project): GeneratedFilesManifestService =
            project.getService(GeneratedFilesManifestService::class.java)
    }

    fun recordGeneratedFile(project: Project, absolutePath: Path) {
        if (!absolutePath.isRegularFile()) return

        val outputRoot = resolveOutputRoot(project) ?: return
        val normalized = absolutePath.normalize()
        val rootNorm = outputRoot.normalize()
        if (!normalized.startsWith(rootNorm)) return

        val rel = rootNorm.relativize(normalized).toString()
        val bytes = runCatching { Files.readAllBytes(normalized) }.getOrNull() ?: return
        val record = Record(
            relativePath = rel,
            sha256 = sha256Hex(bytes),
            sizeBytes = bytes.size.toLong()
        )

        synchronized(lock) {
            val persisted = load(project, outputRoot)
            val map = persisted.records.associateBy { it.relativePath }.toMutableMap()
            map[rel] = record
            save(project, outputRoot, Persisted(records = map.values.sortedBy { it.relativePath }))
        }
    }

    /**
     * Deletes ONLY files recorded in manifest whose current content hash matches the recorded hash.
     * If a file is missing, it's removed from the manifest.
     */
    fun cleanupGeneratedFiles(project: Project): CleanupResult {
        val outputRoot = resolveOutputRoot(project) ?: return CleanupResult(0, 0, 0, 0)

        var deleted = 0
        var skippedModified = 0
        var skippedMissing = 0
        var errors = 0

        synchronized(lock) {
            val persisted = load(project, outputRoot)
            val kept = mutableListOf<Record>()

            for (r in persisted.records) {
                val target = outputRoot.resolve(r.relativePath).normalize()
                if (!target.startsWith(outputRoot.normalize())) {
                    // defensive: never delete outside output root
                    kept.add(r)
                    continue
                }

                if (!target.exists()) {
                    skippedMissing++
                    continue
                }

                val bytes = runCatching { Files.readAllBytes(target) }.getOrNull()
                if (bytes == null) {
                    errors++
                    kept.add(r)
                    continue
                }

                val currentHash = sha256Hex(bytes)
                if (currentHash != r.sha256) {
                    skippedModified++
                    kept.add(r)
                    continue
                }

                val ok = runCatching { target.deleteIfExists() }.getOrDefault(false)
                if (ok) deleted++ else {
                    errors++
                    kept.add(r)
                }
            }

            if (kept.isEmpty()) {
                runCatching { manifestPath(outputRoot).deleteIfExists() }
            } else {
                save(project, outputRoot, Persisted(records = kept.sortedBy { it.relativePath }))
            }
        }

        return CleanupResult(deleted, skippedModified, skippedMissing, errors)
    }

    private fun resolveOutputRoot(project: Project): Path? {
        val settings = ReportPluginSettings.getInstance().state
        val projectRoot = project.basePath?.let { Path(it) } ?: return null
        return if (!settings.outputDir.isNullOrBlank()) projectRoot.resolve(settings.outputDir) else projectRoot.resolve("docs")
    }

    private fun manifestPath(outputRoot: Path): Path =
        outputRoot.resolve(".logic-code").resolve("manifest.json")

    private fun load(project: Project, outputRoot: Path): Persisted {
        val file = manifestPath(outputRoot)
        if (!file.exists()) return Persisted()
        return runCatching {
            val json = file.readText(Charsets.UTF_8)
            gson.fromJson(json, Persisted::class.java) ?: Persisted()
        }.getOrElse { Persisted() }
    }

    private fun save(project: Project, outputRoot: Path, persisted: Persisted) {
        val file = manifestPath(outputRoot)
        file.parent.createDirectories()
        val tmp = file.parent.resolve("${file.fileName}.tmp")
        val json = gson.toJson(persisted)
        runCatching {
            tmp.writeText(json, Charsets.UTF_8)
            Files.move(tmp, file, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE)
        }.onFailure {
            runCatching {
                tmp.writeText(json, Charsets.UTF_8)
                Files.move(tmp, file, StandardCopyOption.REPLACE_EXISTING)
            }
        }
    }

    private fun sha256Hex(bytes: ByteArray): String {
        val digest = MessageDigest.getInstance("SHA-256").digest(bytes)
        val sb = StringBuilder(digest.size * 2)
        for (b in digest) sb.append("%02x".format(b))
        return sb.toString()
    }
}

